[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "lgbeam"
version = "0.1.0"
description = "Laguerre-Gaussian beam generation library"
authors = [
    {name = "Marcin Marzejon"}
]
requires-python = ">=3.10"

dependencies = [
    "numpy>=2.0",
    "scipy>=1.14",
    "matplotlib>=3.9",
]

[tool.setuptools]
package-dir = {"" = "src/lg-mode-classifier"}

[tool.setuptools.packages.find]
where = ["src/lg-mode-classifier"]
include = ["lgbeam*"]